7-module solution
js-tasks-ru/jsbasic-20230116-2_potyomkin-m pull request #10
Opened 2023-02-15 13:18 UTC by potyomkin

2023-02-15 13:19 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-02-15 14:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-02-16 09:57 UTC, SinimaWath requested changes

2023-02-16 09:57 UTC, SinimaWath commented on 7-module/1-task/index.js
> +    `;
```
Можно заменить на один шаблон, если использовать шаблонный строки
const ribbon = `
      <div class="ribbon">
        <!--Кнопка прокрутки влево-->
        <button class="ribbon__arrow ribbon__arrow_left">
          <img src="/assets/images/icons/angle-icon.svg" alt="icon">
        </button>
        <!--Ссылки на категории-->
        <nav class="ribbon__inner">
        
        ${categories.map(({ id, name }) => `<a href="#" class="ribbon__item" data-id="${id}">${name}</a>`).join('')}
        
         </nav>
        <!--Кнопка прокрутки вправо-->
        <button class="ribbon__arrow ribbon__arrow_right ribbon__arrow_visible">
          <img src="/assets/images/icons/angle-icon.svg" alt="icon">
        </button>
      </div>

`;

```

2023-02-16 09:57 UTC, SinimaWath commented on 7-module/1-task/index.js
> +    ribbonInner.addEventListener('scroll', (e) => {
Странно, что обработчик события scroll, вещается после клика. 

Он не должен зависеть от клика, так же в этой ситуции у тебя бесконечно генерируются новые scroll обработчики

2023-02-16 10:45 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-02-19 07:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-02-20 13:31 UTC, SinimaWath approved these changes

2023-02-20 13:32 UTC, merged