4-module solution
js-tasks-ru/jsbasic-20230116-2_potyomkin-m pull request #7
Opened 2023-01-27 13:08 UTC by potyomkin

2023-01-27 13:10 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-01-29 14:31 UTC, SinimaWath requested changes

2023-01-29 14:31 UTC, SinimaWath commented on 4-module/3-task/index.js
> +    row.cells[3].dataset.available === 'false' ? row.cells[3].parentNode.classList.add('unavailable') : row.cells[3].dataset.available === undefined ? row.cells[3].parentNode.setAttribute('hidden', '
Такое очень сложно читать, вложенные тернарные операторы обычно запрещены

2023-01-29 14:32 UTC, SinimaWath approved these changes

2023-01-29 14:32 UTC, merged